// <auto-generated />
using System;
using BatailleNavaleApp.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BatailleNavaleApp.Migrations
{
    [DbContext(typeof(BattleShipGameContext))]
    partial class BattleShipGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("BatailleNavaleApp.Entities.BattleShipGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Player1Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("BattleShipGames");
                });

            modelBuilder.Entity("BatailleNavaleApp.Entities.BoardCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BoardCoordinatesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BoardGameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CellOccupant")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ShipId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardCoordinatesId");

                    b.HasIndex("BoardGameId");

                    b.HasIndex("ShipId");

                    b.ToTable("BoardCells");
                });

            modelBuilder.Entity("BatailleNavaleApp.Entities.BoardCoordinates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("x")
                        .HasColumnType("INTEGER");

                    b.Property<int>("y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BoardCoordinates");
                });

            modelBuilder.Entity("BatailleNavaleApp.Entities.BoardGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BoardGames");
                });

            modelBuilder.Entity("BatailleNavaleApp.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnnemyBoardGameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PersonnalBoardGameId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnnemyBoardGameId");

                    b.HasIndex("PersonnalBoardGameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BatailleNavaleApp.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Damages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("BatailleNavaleApp.Entities.BattleShipGame", b =>
                {
                    b.HasOne("BatailleNavaleApp.Entities.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id");

                    b.HasOne("BatailleNavaleApp.Entities.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id");
                });

            modelBuilder.Entity("BatailleNavaleApp.Entities.BoardCell", b =>
                {
                    b.HasOne("BatailleNavaleApp.Entities.BoardCoordinates", "BoardCoordinates")
                        .WithMany()
                        .HasForeignKey("BoardCoordinatesId");

                    b.HasOne("BatailleNavaleApp.Entities.BoardGame", null)
                        .WithMany("Cells")
                        .HasForeignKey("BoardGameId");

                    b.HasOne("BatailleNavaleApp.Ship", null)
                        .WithMany("OccupedCells")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("BatailleNavaleApp.Entities.Player", b =>
                {
                    b.HasOne("BatailleNavaleApp.Entities.BoardGame", "EnnemyBoardGame")
                        .WithMany()
                        .HasForeignKey("EnnemyBoardGameId");

                    b.HasOne("BatailleNavaleApp.Entities.BoardGame", "PersonnalBoardGame")
                        .WithMany()
                        .HasForeignKey("PersonnalBoardGameId");
                });

            modelBuilder.Entity("BatailleNavaleApp.Ship", b =>
                {
                    b.HasOne("BatailleNavaleApp.Entities.Player", null)
                        .WithMany("Ships")
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
